# Generated by Django 3.2.8 on 2021-10-15 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='perfil',
            field=models.CharField(default='analista', max_length=13),
        ),
    ]
