# Generated by Django 3.2.8 on 2021-10-15 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_alter_empleado_perfil'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solicitud_credito',
            old_name='visto',
            new_name='evaluado',
        ),
    ]
